"""
NexusNotes — Attachment ORM Model

Stores metadata for files uploaded and associated with notes.
Actual file bytes are stored in S3/MinIO — NOT in MySQL.

Key fields:
- object_key: The S3 object key (path within the bucket)
- bucket_name: The S3 bucket (allows multi-bucket setups in future)
- original_filename: The user's original filename (for display only)
- content_type: MIME type (validated on upload)
- file_size: In bytes
- width/height: For images (null for non-image attachments)

Security:
- object_key is generated by the server (UUID-based), never from user input
- original_filename is display-only and never used for storage
"""

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Attachment(Base):
    __tablename__ = "attachments"

    __table_args__ = (
        Index("idx_attachments_user_id", "user_id"),
        Index("idx_attachments_note_id", "note_id"),
        Index("idx_attachments_object_key", "object_key", mysql_length=191),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    note_id: Mapped[int | None] = mapped_column(
        ForeignKey("notes.id", ondelete="SET NULL"), nullable=True
    )
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)
    object_key: Mapped[str] = mapped_column(String(1000), nullable=False)
    bucket_name: Mapped[str] = mapped_column(String(255), nullable=False)
    content_type: Mapped[str] = mapped_column(String(100), nullable=False)
    file_size: Mapped[int] = mapped_column(Integer, nullable=False)  # bytes
    width: Mapped[int | None] = mapped_column(Integer, nullable=True)   # pixels
    height: Mapped[int | None] = mapped_column(Integer, nullable=True)  # pixels
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="attachments")
    note: Mapped["Note | None"] = relationship("Note", back_populates="attachments")

    def __repr__(self) -> str:
        return f"<Attachment id={self.id} key={self.object_key!r}>"
